/**
 * 长管用户
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from "./models";

/**
 * @property `[expireTime]`
 * @property `[ipaddr]`
 * @property `[loginTime]`
 * @property `[permissions]`
 * @property `[roles]`
 * @property `[sysUser]`
 * @property `[token]`
 * @property `[userid]`
 * @property `[username]`
 */
export interface LoginUser {
  expireTime?: number;
  ipaddr?: string;
  loginTime?: number;
  permissions?: Array<string>;
  roles?: Array<string>;
  sysUser?: models.SysUserRes;
  token?: string;
  userid?: number;
  username?: string;
}
