export * from './LoginUser';
export * from './RLoginUser';
export * from './Rboolean';
export * from './SysDept';
export * from './SysMenu';
export * from './SysRole';
export * from './SysRoleReq';
export * from './SysRoleRes';
export * from './SysUserReq';
export * from './SysUserRes';
export * from './SysUserRole';
export * from './TableDataInfo';
export type ModelInteger = number;
export type ModelFloat = number;
export type LocalDate = Date;