/**
 * 长管用户
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from "./models";

/**
 * @description 部门表
 * @property `[ancestors]` 祖级列表
 * @property `[children]`
 * @property `[createBy]` 创建者
 * @property `[createTime]` 创建时间
 * @property `[delFlag]` 删除标志（0代表存在 2代表删除）
 * @property `[deptId]` 部门id
 * @property `[deptName]` 部门名称
 * @property `[email]` 邮箱
 * @property `[leaderId]` 负责人
 * @property `[orderNum]` 显示顺序
 * @property `[parentId]` 父部门id
 * @property `[parentName]` 父部门名称
 * @property `[phone]` 联系电话
 * @property `[status]` 部门状态（0正常 1停用）
 * @property `[updateBy]` 更新者
 * @property `[updateTime]` 更新时间
 */
export interface SysDept {
  /**
   * 祖级列表
   */
  ancestors?: string;
  children?: Array<models.SysDept>;
  /**
   * 创建者
   */
  createBy?: string;
  /**
   * 创建时间
   */
  createTime?: Date;
  /**
   * 删除标志（0代表存在 2代表删除）
   */
  delFlag?: string;
  /**
   * 部门id
   */
  deptId?: number;
  /**
   * 部门名称
   */
  deptName?: string;
  /**
   * 邮箱
   */
  email?: string;
  /**
   * 负责人
   */
  leaderId?: number;
  /**
   * 显示顺序
   */
  orderNum?: number;
  /**
   * 父部门id
   */
  parentId?: number;
  /**
   * 父部门名称
   */
  parentName?: string;
  /**
   * 联系电话
   */
  phone?: string;
  /**
   * 部门状态（0正常 1停用）
   */
  status?: string;
  /**
   * 更新者
   */
  updateBy?: string;
  /**
   * 更新时间
   */
  updateTime?: Date;
}
