/**
 * 长管用户
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @description 角色信息表
  * @property `[admin]` 
  * @property `[createBy]` 创建者
  * @property `[createTime]` 创建时间
  * @property `[dataScope]` 数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）
  * @property `[delFlag]` 删除标志（0代表存在 2代表删除）
  * @property `[deptCheckStrictly]` 部门树选择项是否关联显示
  * @property `[deptIds]` 
  * @property `[flag]` 
  * @property `[menuCheckStrictly]` 菜单树选择项是否关联显示
  * @property `[menuIds]` 
  * @property `[permissions]` 
  * @property `[remark]` 备注
  * @property `[roleId]` 角色ID
  * @property `[roleKey]` 角色编码
  * @property `[roleName]` 角色名称
  * @property `[roleSort]` 显示顺序
  * @property `[status]` 角色状态（0正常 1停用）
  * @property `[updateBy]` 更新者
  * @property `[updateTime]` 更新时间
  */
export interface SysRoleRes {
  "admin"?: boolean;
  /**
   * 创建者
   */
  "createBy"?: string;
  /**
   * 创建时间
   */
  "createTime"?: Date;
  /**
   * 数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）
   */
  "dataScope"?: string;
  /**
   * 删除标志（0代表存在 2代表删除）
   */
  "delFlag"?: string;
  /**
   * 部门树选择项是否关联显示
   */
  "deptCheckStrictly"?: boolean;
  "deptIds"?: Array<number>;
  "flag"?: boolean;
  /**
   * 菜单树选择项是否关联显示
   */
  "menuCheckStrictly"?: boolean;
  "menuIds"?: Array<number>;
  "permissions"?: Array<string>;
  /**
   * 备注
   */
  "remark"?: string;
  /**
   * 角色ID
   */
  "roleId"?: number;
  /**
   * 角色编码
   */
  "roleKey"?: string;
  /**
   * 角色名称
   */
  "roleName"?: string;
  /**
   * 显示顺序
   */
  "roleSort"?: number;
  /**
   * 角色状态（0正常 1停用）
   */
  "status"?: string;
  /**
   * 更新者
   */
  "updateBy"?: string;
  /**
   * 更新时间
   */
  "updateTime"?: Date;
}

