/**
 * 长管用户
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @description 用户和角色关联表
  * @property `[roleId]` 角色ID
  * @property `[userId]` 用户ID
  */
export interface SysUserRole {
  /**
   * 角色ID
   */
  "roleId"?: number;
  /**
   * 用户ID
   */
  "userId"?: number;
}

